name = "Guhs Pack"
author = "Juiced"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5244d6fa6d1108e5843a83a554c7201e2b70f7e9b8a68e8d3e68bf8ec0519eb3"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.112"
