name = "Guhs Pack"
author = "Juiced"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f197e4833fdcd1f883fc1dac5c8fe22707ed8cfe47f354b905d1db816516523"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.112"
