name = "Guhs Pack"
author = "Juiced"
version = "1.2.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db4494fb3bdf200201e67b01e2225ae377d21934ee87b4576fd241663fe114f5"

[versions]
minecraft = "26.1.2"
neoforge = "26.1.2.112"
